#!/bin/sh

lsof | grep *:http-alt || node-inspector &

make && sleep 1s && gnome-open http://0.0.0.0:8080/debug?port=5858 &

TZ=/usr/share/zoneinfo/UTC NODE_ENV=development DEBUG=* node --debug-brk server.js 

